export interface CountryConfig {
  code: string;
  name: string;
  labels: {
    addressLine1: string;
    addressLine2: string;
    city: string;
    region: string;
    postalCode: string;
  };
  required: {
    region: boolean;
    postalCode: boolean;
  };
  postalCodePattern?: string;
  postalCodePlaceholder?: string;
  fieldOrder: ('addressLine1' | 'addressLine2' | 'city' | 'region' | 'postalCode')[];
}

export const countries: CountryConfig[] = [
  {
    code: 'FR',
    name: 'France',
    labels: {
      addressLine1: 'Adresse',
      addressLine2: 'Complément d\'adresse',
      city: 'Ville',
      region: 'Département',
      postalCode: 'Code postal',
    },
    required: { region: false, postalCode: true },
    postalCodePattern: '^[0-9]{5}$',
    postalCodePlaceholder: '75001',
    fieldOrder: ['addressLine1', 'addressLine2', 'postalCode', 'city'],
  },
  {
    code: 'BE',
    name: 'Belgique',
    labels: {
      addressLine1: 'Adresse',
      addressLine2: 'Complément',
      city: 'Localité',
      region: 'Province',
      postalCode: 'Code postal',
    },
    required: { region: false, postalCode: true },
    postalCodePattern: '^[0-9]{4}$',
    postalCodePlaceholder: '1000',
    fieldOrder: ['addressLine1', 'addressLine2', 'postalCode', 'city'],
  },
  {
    code: 'CH',
    name: 'Suisse',
    labels: {
      addressLine1: 'Adresse',
      addressLine2: 'Complément',
      city: 'Localité',
      region: 'Canton',
      postalCode: 'NPA',
    },
    required: { region: false, postalCode: true },
    postalCodePattern: '^[0-9]{4}$',
    postalCodePlaceholder: '1200',
    fieldOrder: ['addressLine1', 'addressLine2', 'postalCode', 'city'],
  },
  {
    code: 'US',
    name: 'États-Unis',
    labels: {
      addressLine1: 'Street address',
      addressLine2: 'Apt, suite, etc.',
      city: 'City',
      region: 'State',
      postalCode: 'ZIP code',
    },
    required: { region: true, postalCode: true },
    postalCodePattern: '^[0-9]{5}(-[0-9]{4})?$',
    postalCodePlaceholder: '10001',
    fieldOrder: ['addressLine1', 'addressLine2', 'city', 'region', 'postalCode'],
  },
  {
    code: 'GB',
    name: 'Royaume-Uni',
    labels: {
      addressLine1: 'Address line 1',
      addressLine2: 'Address line 2',
      city: 'Town/City',
      region: 'County',
      postalCode: 'Postcode',
    },
    required: { region: false, postalCode: true },
    postalCodePattern: '^[A-Z]{1,2}[0-9][A-Z0-9]? ?[0-9][A-Z]{2}$',
    postalCodePlaceholder: 'SW1A 1AA',
    fieldOrder: ['addressLine1', 'addressLine2', 'city', 'region', 'postalCode'],
  },
  {
    code: 'DE',
    name: 'Allemagne',
    labels: {
      addressLine1: 'Straße und Hausnummer',
      addressLine2: 'Adresszusatz',
      city: 'Stadt',
      region: 'Bundesland',
      postalCode: 'PLZ',
    },
    required: { region: false, postalCode: true },
    postalCodePattern: '^[0-9]{5}$',
    postalCodePlaceholder: '10115',
    fieldOrder: ['addressLine1', 'addressLine2', 'postalCode', 'city'],
  },
  {
    code: 'ES',
    name: 'Espagne',
    labels: {
      addressLine1: 'Dirección',
      addressLine2: 'Piso, puerta',
      city: 'Localidad',
      region: 'Provincia',
      postalCode: 'Código postal',
    },
    required: { region: true, postalCode: true },
    postalCodePattern: '^[0-9]{5}$',
    postalCodePlaceholder: '28001',
    fieldOrder: ['addressLine1', 'addressLine2', 'postalCode', 'city', 'region'],
  },
  {
    code: 'IT',
    name: 'Italie',
    labels: {
      addressLine1: 'Indirizzo',
      addressLine2: 'Interno, scala',
      city: 'Città',
      region: 'Provincia',
      postalCode: 'CAP',
    },
    required: { region: true, postalCode: true },
    postalCodePattern: '^[0-9]{5}$',
    postalCodePlaceholder: '00100',
    fieldOrder: ['addressLine1', 'addressLine2', 'postalCode', 'city', 'region'],
  },
  {
    code: 'IE',
    name: 'Irlande',
    labels: {
      addressLine1: 'Address line 1',
      addressLine2: 'Address line 2',
      city: 'Town/City',
      region: 'County',
      postalCode: 'Eircode',
    },
    required: { region: true, postalCode: false },
    postalCodePattern: '^[A-Z0-9]{3} ?[A-Z0-9]{4}$',
    postalCodePlaceholder: 'D02 X285',
    fieldOrder: ['addressLine1', 'addressLine2', 'city', 'region', 'postalCode'],
  },
  {
    code: 'CA',
    name: 'Canada',
    labels: {
      addressLine1: 'Street address',
      addressLine2: 'Apt, suite, etc.',
      city: 'City',
      region: 'Province',
      postalCode: 'Postal code',
    },
    required: { region: true, postalCode: true },
    postalCodePattern: '^[A-Z][0-9][A-Z] ?[0-9][A-Z][0-9]$',
    postalCodePlaceholder: 'H2X 1Y4',
    fieldOrder: ['addressLine1', 'addressLine2', 'city', 'region', 'postalCode'],
  },
  {
    code: 'JP',
    name: 'Japon',
    labels: {
      addressLine1: 'Adresse',
      addressLine2: 'Bâtiment, étage',
      city: 'Ville',
      region: 'Préfecture',
      postalCode: 'Code postal',
    },
    required: { region: true, postalCode: true },
    postalCodePattern: '^[0-9]{3}-?[0-9]{4}$',
    postalCodePlaceholder: '100-0001',
    fieldOrder: ['postalCode', 'region', 'city', 'addressLine1', 'addressLine2'],
  },
  {
    code: 'CN',
    name: 'Chine',
    labels: {
      addressLine1: 'Adresse',
      addressLine2: 'Complément',
      city: 'Ville',
      region: 'Province',
      postalCode: 'Code postal',
    },
    required: { region: true, postalCode: true },
    postalCodePattern: '^[0-9]{6}$',
    postalCodePlaceholder: '100000',
    fieldOrder: ['postalCode', 'region', 'city', 'addressLine1', 'addressLine2'],
  },
  {
    code: 'RU',
    name: 'Russie',
    labels: {
      addressLine1: 'Adresse',
      addressLine2: 'Complément',
      city: 'Ville',
      region: 'Région/Oblast',
      postalCode: 'Index postal',
    },
    required: { region: true, postalCode: true },
    postalCodePattern: '^[0-9]{6}$',
    postalCodePlaceholder: '101000',
    fieldOrder: ['postalCode', 'region', 'city', 'addressLine1', 'addressLine2'],
  },
  {
    code: 'BR',
    name: 'Brésil',
    labels: {
      addressLine1: 'Endereço',
      addressLine2: 'Complemento',
      city: 'Cidade',
      region: 'Estado',
      postalCode: 'CEP',
    },
    required: { region: true, postalCode: true },
    postalCodePattern: '^[0-9]{5}-?[0-9]{3}$',
    postalCodePlaceholder: '01310-100',
    fieldOrder: ['addressLine1', 'addressLine2', 'city', 'region', 'postalCode'],
  },
  {
    code: 'AU',
    name: 'Australie',
    labels: {
      addressLine1: 'Street address',
      addressLine2: 'Unit, level',
      city: 'Suburb',
      region: 'State',
      postalCode: 'Postcode',
    },
    required: { region: true, postalCode: true },
    postalCodePattern: '^[0-9]{4}$',
    postalCodePlaceholder: '2000',
    fieldOrder: ['addressLine1', 'addressLine2', 'city', 'region', 'postalCode'],
  },
  {
    code: 'MX',
    name: 'Mexique',
    labels: {
      addressLine1: 'Calle y número',
      addressLine2: 'Colonia',
      city: 'Ciudad',
      region: 'Estado',
      postalCode: 'Código postal',
    },
    required: { region: true, postalCode: true },
    postalCodePattern: '^[0-9]{5}$',
    postalCodePlaceholder: '06600',
    fieldOrder: ['addressLine1', 'addressLine2', 'postalCode', 'city', 'region'],
  },
  {
    code: 'IN',
    name: 'Inde',
    labels: {
      addressLine1: 'Address',
      addressLine2: 'Landmark',
      city: 'City',
      region: 'State',
      postalCode: 'PIN code',
    },
    required: { region: true, postalCode: true },
    postalCodePattern: '^[0-9]{6}$',
    postalCodePlaceholder: '110001',
    fieldOrder: ['addressLine1', 'addressLine2', 'city', 'region', 'postalCode'],
  },
  {
    code: 'KR',
    name: 'Corée du Sud',
    labels: {
      addressLine1: 'Adresse',
      addressLine2: 'Détail',
      city: 'Ville',
      region: 'Province',
      postalCode: 'Code postal',
    },
    required: { region: false, postalCode: true },
    postalCodePattern: '^[0-9]{5}$',
    postalCodePlaceholder: '03141',
    fieldOrder: ['postalCode', 'city', 'addressLine1', 'addressLine2'],
  },
  {
    code: 'NL',
    name: 'Pays-Bas',
    labels: {
      addressLine1: 'Straat en huisnummer',
      addressLine2: 'Toevoeging',
      city: 'Plaats',
      region: 'Provincie',
      postalCode: 'Postcode',
    },
    required: { region: false, postalCode: true },
    postalCodePattern: '^[0-9]{4} ?[A-Z]{2}$',
    postalCodePlaceholder: '1012 AB',
    fieldOrder: ['addressLine1', 'addressLine2', 'postalCode', 'city'],
  },
  {
    code: 'PL',
    name: 'Pologne',
    labels: {
      addressLine1: 'Ulica i numer',
      addressLine2: 'Lokal',
      city: 'Miasto',
      region: 'Województwo',
      postalCode: 'Kod pocztowy',
    },
    required: { region: false, postalCode: true },
    postalCodePattern: '^[0-9]{2}-[0-9]{3}$',
    postalCodePlaceholder: '00-001',
    fieldOrder: ['addressLine1', 'addressLine2', 'postalCode', 'city'],
  },
  {
    code: 'PT',
    name: 'Portugal',
    labels: {
      addressLine1: 'Morada',
      addressLine2: 'Complemento',
      city: 'Localidade',
      region: 'Distrito',
      postalCode: 'Código postal',
    },
    required: { region: false, postalCode: true },
    postalCodePattern: '^[0-9]{4}-[0-9]{3}$',
    postalCodePlaceholder: '1000-001',
    fieldOrder: ['addressLine1', 'addressLine2', 'postalCode', 'city'],
  },
  {
    code: 'SE',
    name: 'Suède',
    labels: {
      addressLine1: 'Gatuadress',
      addressLine2: 'C/o',
      city: 'Ort',
      region: 'Län',
      postalCode: 'Postnummer',
    },
    required: { region: false, postalCode: true },
    postalCodePattern: '^[0-9]{3} ?[0-9]{2}$',
    postalCodePlaceholder: '111 22',
    fieldOrder: ['addressLine1', 'addressLine2', 'postalCode', 'city'],
  },
  {
    code: 'NO',
    name: 'Norvège',
    labels: {
      addressLine1: 'Gateadresse',
      addressLine2: 'C/o',
      city: 'Poststed',
      region: 'Fylke',
      postalCode: 'Postnummer',
    },
    required: { region: false, postalCode: true },
    postalCodePattern: '^[0-9]{4}$',
    postalCodePlaceholder: '0150',
    fieldOrder: ['addressLine1', 'addressLine2', 'postalCode', 'city'],
  },
  {
    code: 'DK',
    name: 'Danemark',
    labels: {
      addressLine1: 'Vejnavn og nummer',
      addressLine2: 'Etage/dør',
      city: 'By',
      region: 'Region',
      postalCode: 'Postnummer',
    },
    required: { region: false, postalCode: true },
    postalCodePattern: '^[0-9]{4}$',
    postalCodePlaceholder: '1000',
    fieldOrder: ['addressLine1', 'addressLine2', 'postalCode', 'city'],
  },
  {
    code: 'FI',
    name: 'Finlande',
    labels: {
      addressLine1: 'Katuosoite',
      addressLine2: 'Lisätiedot',
      city: 'Kaupunki',
      region: 'Maakunta',
      postalCode: 'Postinumero',
    },
    required: { region: false, postalCode: true },
    postalCodePattern: '^[0-9]{5}$',
    postalCodePlaceholder: '00100',
    fieldOrder: ['addressLine1', 'addressLine2', 'postalCode', 'city'],
  },
  {
    code: 'AT',
    name: 'Autriche',
    labels: {
      addressLine1: 'Straße und Hausnummer',
      addressLine2: 'Zusatz',
      city: 'Ort',
      region: 'Bundesland',
      postalCode: 'PLZ',
    },
    required: { region: false, postalCode: true },
    postalCodePattern: '^[0-9]{4}$',
    postalCodePlaceholder: '1010',
    fieldOrder: ['addressLine1', 'addressLine2', 'postalCode', 'city'],
  },
  {
    code: 'GR',
    name: 'Grèce',
    labels: {
      addressLine1: 'Διεύθυνση',
      addressLine2: 'Όροφος',
      city: 'Πόλη',
      region: 'Περιφέρεια',
      postalCode: 'Τ.Κ.',
    },
    required: { region: false, postalCode: true },
    postalCodePattern: '^[0-9]{3} ?[0-9]{2}$',
    postalCodePlaceholder: '105 57',
    fieldOrder: ['addressLine1', 'addressLine2', 'postalCode', 'city'],
  },
  {
    code: 'CZ',
    name: 'Tchéquie',
    labels: {
      addressLine1: 'Ulice a číslo',
      addressLine2: 'Doplněk',
      city: 'Město',
      region: 'Kraj',
      postalCode: 'PSČ',
    },
    required: { region: false, postalCode: true },
    postalCodePattern: '^[0-9]{3} ?[0-9]{2}$',
    postalCodePlaceholder: '110 00',
    fieldOrder: ['addressLine1', 'addressLine2', 'postalCode', 'city'],
  },
  {
    code: 'ZA',
    name: 'Afrique du Sud',
    labels: {
      addressLine1: 'Street address',
      addressLine2: 'Suburb',
      city: 'City',
      region: 'Province',
      postalCode: 'Postal code',
    },
    required: { region: true, postalCode: true },
    postalCodePattern: '^[0-9]{4}$',
    postalCodePlaceholder: '2001',
    fieldOrder: ['addressLine1', 'addressLine2', 'city', 'region', 'postalCode'],
  },
  {
    code: 'MA',
    name: 'Maroc',
    labels: {
      addressLine1: 'Adresse',
      addressLine2: 'Complément',
      city: 'Ville',
      region: 'Région',
      postalCode: 'Code postal',
    },
    required: { region: false, postalCode: true },
    postalCodePattern: '^[0-9]{5}$',
    postalCodePlaceholder: '20000',
    fieldOrder: ['addressLine1', 'addressLine2', 'postalCode', 'city'],
  },
  {
    code: 'TN',
    name: 'Tunisie',
    labels: {
      addressLine1: 'Adresse',
      addressLine2: 'Complément',
      city: 'Ville',
      region: 'Gouvernorat',
      postalCode: 'Code postal',
    },
    required: { region: false, postalCode: true },
    postalCodePattern: '^[0-9]{4}$',
    postalCodePlaceholder: '1000',
    fieldOrder: ['addressLine1', 'addressLine2', 'postalCode', 'city'],
  },
  {
    code: 'SN',
    name: 'Sénégal',
    labels: {
      addressLine1: 'Adresse',
      addressLine2: 'Quartier',
      city: 'Ville',
      region: 'Région',
      postalCode: 'Code postal',
    },
    required: { region: false, postalCode: false },
    postalCodePattern: '^[0-9]{5}$',
    postalCodePlaceholder: '10000',
    fieldOrder: ['addressLine1', 'addressLine2', 'city', 'region'],
  },
  {
    code: 'CI',
    name: 'Côte d\'Ivoire',
    labels: {
      addressLine1: 'Adresse',
      addressLine2: 'Quartier',
      city: 'Ville',
      region: 'Région',
      postalCode: 'Code postal',
    },
    required: { region: false, postalCode: false },
    fieldOrder: ['addressLine1', 'addressLine2', 'city', 'region'],
  },
  {
    code: 'LU',
    name: 'Luxembourg',
    labels: {
      addressLine1: 'Adresse',
      addressLine2: 'Complément',
      city: 'Localité',
      region: 'Canton',
      postalCode: 'Code postal',
    },
    required: { region: false, postalCode: true },
    postalCodePattern: '^[0-9]{4}$',
    postalCodePlaceholder: '1234',
    fieldOrder: ['addressLine1', 'addressLine2', 'postalCode', 'city'],
  },
  {
    code: 'MC',
    name: 'Monaco',
    labels: {
      addressLine1: 'Adresse',
      addressLine2: 'Complément',
      city: 'Ville',
      region: 'Quartier',
      postalCode: 'Code postal',
    },
    required: { region: false, postalCode: true },
    postalCodePattern: '^980[0-9]{2}$',
    postalCodePlaceholder: '98000',
    fieldOrder: ['addressLine1', 'addressLine2', 'postalCode', 'city'],
  },
];

export const getCountryConfig = (code: string): CountryConfig => {
  return countries.find(c => c.code === code) || countries[0]; // Default to France
};

export const usStates = [
  { code: 'AL', name: 'Alabama' }, { code: 'AK', name: 'Alaska' },
  { code: 'AZ', name: 'Arizona' }, { code: 'AR', name: 'Arkansas' },
  { code: 'CA', name: 'California' }, { code: 'CO', name: 'Colorado' },
  { code: 'CT', name: 'Connecticut' }, { code: 'DE', name: 'Delaware' },
  { code: 'FL', name: 'Florida' }, { code: 'GA', name: 'Georgia' },
  { code: 'HI', name: 'Hawaii' }, { code: 'ID', name: 'Idaho' },
  { code: 'IL', name: 'Illinois' }, { code: 'IN', name: 'Indiana' },
  { code: 'IA', name: 'Iowa' }, { code: 'KS', name: 'Kansas' },
  { code: 'KY', name: 'Kentucky' }, { code: 'LA', name: 'Louisiana' },
  { code: 'ME', name: 'Maine' }, { code: 'MD', name: 'Maryland' },
  { code: 'MA', name: 'Massachusetts' }, { code: 'MI', name: 'Michigan' },
  { code: 'MN', name: 'Minnesota' }, { code: 'MS', name: 'Mississippi' },
  { code: 'MO', name: 'Missouri' }, { code: 'MT', name: 'Montana' },
  { code: 'NE', name: 'Nebraska' }, { code: 'NV', name: 'Nevada' },
  { code: 'NH', name: 'New Hampshire' }, { code: 'NJ', name: 'New Jersey' },
  { code: 'NM', name: 'New Mexico' }, { code: 'NY', name: 'New York' },
  { code: 'NC', name: 'North Carolina' }, { code: 'ND', name: 'North Dakota' },
  { code: 'OH', name: 'Ohio' }, { code: 'OK', name: 'Oklahoma' },
  { code: 'OR', name: 'Oregon' }, { code: 'PA', name: 'Pennsylvania' },
  { code: 'RI', name: 'Rhode Island' }, { code: 'SC', name: 'South Carolina' },
  { code: 'SD', name: 'South Dakota' }, { code: 'TN', name: 'Tennessee' },
  { code: 'TX', name: 'Texas' }, { code: 'UT', name: 'Utah' },
  { code: 'VT', name: 'Vermont' }, { code: 'VA', name: 'Virginia' },
  { code: 'WA', name: 'Washington' }, { code: 'WV', name: 'West Virginia' },
  { code: 'WI', name: 'Wisconsin' }, { code: 'WY', name: 'Wyoming' },
];

export const canadaProvinces = [
  { code: 'AB', name: 'Alberta' }, { code: 'BC', name: 'British Columbia' },
  { code: 'MB', name: 'Manitoba' }, { code: 'NB', name: 'New Brunswick' },
  { code: 'NL', name: 'Newfoundland and Labrador' }, { code: 'NS', name: 'Nova Scotia' },
  { code: 'NT', name: 'Northwest Territories' }, { code: 'NU', name: 'Nunavut' },
  { code: 'ON', name: 'Ontario' }, { code: 'PE', name: 'Prince Edward Island' },
  { code: 'QC', name: 'Quebec' }, { code: 'SK', name: 'Saskatchewan' },
  { code: 'YT', name: 'Yukon' },
];

export const getRegionList = (countryCode: string): { code: string; name: string }[] | null => {
  switch (countryCode) {
    case 'US': return usStates;
    case 'CA': return canadaProvinces;
    default: return null;
  }
};
